version: '2'
services:
  nuxeo:
    container_name: nuxeo-connected
    image: nuxeo-hf:10.10-latest
    ports:
    - "8080:8080"
    - "8787:8787"
    - "9200:9200"
    environment:
    - TZ=US/Pacific
    - NUXEO_CLID=${CLID}

